"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](blue)\
$os\
$directory\
[](fg:blue bg:surface0)\
$git_branch\
$git_status\
[](fg:surface0 bg:surface1)\
$rust\
$golang\
$ruby\
$elixir\
$nodejs\
$php\
$python\
[](fg:surface1 bg:surface2)\
$docker_context\
[](fg:surface2 bg:peach)\
$time\
[ ](fg:peach)\
$line_break$character"""

palette = "catppuccin_mocha"

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[os]
disabled = false
style = "bg:blue fg:mantle"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[directory]
style = "fg:mantle bg:blue"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:suface0"
format = '[[ $symbol $branch ](fg:peach bg:surface0)]($style)'

[git_status]
style = "bg:surface0"
format = '[[($all_status$ahead_behind )](fg:peach bg:surface0)]($style)'

[nodejs]
symbol = ""
style = "bg:surface1"
format = '[[ $symbol( $version) ](fg:green bg:surface1)]($style)'

[ruby]
symbol = ""
style = "bg:surface1"
format = '[[ $symbol( $version) ](fg:red bg:surface1)]($style)'

[rust]
symbol = ""
style = "bg:surface1"
format = '[[ $symbol( $version) ](fg:peach bg:surface1)]($style)'

[golang]
symbol = ""
style = "bg:surface1"
format = '[[ $symbol( $version) ](fg:sapphire bg:surface1)]($style)'

[php]
symbol = ""
style = "bg:surface1"
format = '[[ $symbol( $version) ](fg:lavender bg:surface1)]($style)'

[python]
symbol = ""
style = "bg:surface1"
format = '[[ $symbol( $version) ](fg:blue bg:surface1)]($style)'

[elixir]
symbol = ""
style = "bg:surface1"
format = '[[ $symbol( $version) ](fg:lavender bg:surface1)]($style)'

[docker_context]
symbol = "󰡨"
style = "bg:surface2"
format = '[[ $symbol( $context) ](fg:blue bg:surface2)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:peach"
format = '[[  $time](fg:mantle bg:peach)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:green)'
error_symbol = '[](bold fg:red)'
vimcmd_symbol = '[](bold fg:green)'
vimcmd_replace_one_symbol = '[](bold fg:purple)'
vimcmd_replace_symbol = '[](bold fg:purple)'
vimcmd_visual_symbol = '[](bold fg:lavender)'
